%% EG_2D_MAJORITY
% Competitive growth between two assemblies using multiple goal tiles

n = 200;
num_sources = 2;
seed_locations = [ceil(n/2) ceil(n/2)-ceil(n/4); ceil(n/2) ceil(n/2)+ceil(n/4)];
num_goals = 200;
timelimit = 3000;
frameskip = 50;

for trial = 1:2

% Feedback with ECM
dstam(n, figs, root_dir, ...
    'BranchingFactor', 0.25, ...
    'TurningFactor', 0.01, ...
    'Gse', 0.995, ...
    'ECM', [0 2 0.02 0.1 1], ...
    'ShowRun', true, ...
    'ShowECM', false, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'SavePopulations', true, ...
    'ColorCode', [150 230 179; 242 233 78]/255, ...
    'NumSeeds', [num_sources num_goals], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'Feedback', true, ...
    'TimeLimit', timelimit)
end