%% EG_2D_FB_ECM
% 2d mode, growing with feedback and ECM activated

n = 100;
num_sources = 1;
seed_locations = [ceil(n/2) ceil(n/2)];
timelimit = 1000;

% Feedback with ECM
ystam(n, ...
    'BranchingFactor', 0.25, ...
    'TurningFactor', 0.05, ...
    'Gse', 0.95, ...
    'ECM', [5 2 0.02 0.1 0.5], ...
    'ShowRun', true, ...
    'ShowECM', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'SetGoal', [ceil(n/2)+ceil(n/4) ceil(n/2)+ceil(n/4)], ...
    'Continuous', true, ...
    'Feedback', true, ...
    'TimeLimit', timelimit)

% No ECM
ystam(n, ...
    'BranchingFactor', 0.25, ...
    'TurningFactor', 0.05, ...
    'Gse', 0.95, ...
    'ECM', [0 2 0.01 -0.5 0.5], ...
    'ShowRun', true, ...
    'ShowECM', false, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'SetGoal', [ceil(n/2)+ceil(n/4) ceil(n/2)+ceil(n/4)], ...
    'Continuous', true, ...
    'Feedback', true, ...
    'TimeLimit', timelimit)