%% EG_2D
% Testing radial mode with ECM and different branching, turning
% concentrations
n = 500;

% Large grid, Ecm saved
ystam(n, ...
    'BranchingFactor', 0.10, ...
    'TurningFactor', 0.05, ...
    'Gse', 0.95, ...
    'ECM', [5 2 0.01 -0.25 0.5], ...
    'ShowRun', true, ...
    'ShowECM', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)

% No branching, no turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 0, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)

% Branching, no turning
ystam(n, ...
    'BranchingFactor', 0.5, ...
    'TurningFactor', 0, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)

% No branching, max turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 1, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)

% No branching, some turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 0.05, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)

% Branching, some turning
ystam(n, ...
    'BranchingFactor', 0.5, ...
    'TurningFactor', 0.05, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [1 1], ...
    'SetRoot', [ceil(n/2)  ceil(n/2)], ...
    'Continuous', true, ...
    'TimeLimit', 200)