%% EG_2D_MULTISEEDS
% Manual source tile placement to create different nucleation patterns

%% Square, 8 tiles
% num_sources = 8;
% seed_locations = [ceil(n/2)+2 ceil(n/2)+2;...
%     ceil(n/2) ceil(n/2)+2;...
%     ceil(n/2)-2 ceil(n/2)+2;...
%     ceil(n/2)+2 ceil(n/2);...
%     ceil(n/2)-2 ceil(n/2);...
%     ceil(n/2)-2 ceil(n/2)-2;...
%     ceil(n/2)+2 ceil(n/2)-2;...
%     ceil(n/2) ceil(n/2)-2];

%% Diamond, radius 3
% num_sources = 12;
% seed_locations = ...
%     [ceil(n/2)+0 ceil(n/2)+3;...
%     ceil(n/2)+1 ceil(n/2)+2;...
%     ceil(n/2)+2 ceil(n/2)+1;...
%     ceil(n/2)+3 ceil(n/2)+0;...
%     ceil(n/2)+2 ceil(n/2)-1;...
%     ceil(n/2)+1 ceil(n/2)-2;...
%     ceil(n/2)+0 ceil(n/2)-3;...
%     ceil(n/2)-1 ceil(n/2)-2;...
%     ceil(n/2)-2 ceil(n/2)-1;...
%     ceil(n/2)-3 ceil(n/2)+0;...
%     ceil(n/2)-2 ceil(n/2)+1;...
%     ceil(n/2)-1 ceil(n/2)+2];

%% Scattered, spread at 5 points
num_sources = 5;
seed_locations = [ceil(n/2) ceil(n/2);...
    ceil(n/2)+ceil(n/2)/2 ceil(n/2)+ceil(n/2)/2;...
    ceil(n/2)+ceil(n/2)/2 ceil(n/2)-ceil(n/2)/2;...
    ceil(n/2)-ceil(n/2)/2 ceil(n/2)+ceil(n/2)/2;...
    ceil(n/2)-ceil(n/2)/2 ceil(n/2)-ceil(n/2)/2];

n = 200;
timelimit = 100;
frameskip = 10;

% No branching, no turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 0, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'TimeLimit', timelimit)

% Branching, no turning
ystam(n, ...
    'BranchingFactor', 0.25, ...
    'TurningFactor', 0, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'TimeLimit', timelimit)

% No branching, max turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 1, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'TimeLimit', timelimit)

% No branching, some turning
ystam(n, ...
    'BranchingFactor', 0, ...
    'TurningFactor', 0.05, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'TimeLimit', timelimit)

% Branching, some turning
ystam(n, ...
    'BranchingFactor', 0.25, ...
    'TurningFactor', 0.05, ...
    'Gse', 1.0, ...
    'ShowRun', true, ...
    'MaxTrials', 1, ...
    'GrowthMode', 'radial', ...
    'NumSeeds', [num_sources 1], ...
    'SetRoot', seed_locations, ...
    'Continuous', true, ...
    'TimeLimit', timelimit)