%% EG_GOMPERTZ
% Tests branching factor vs space-filling

n = 300;
num_sources = 1;
seed_locations = [ceil(n/2) ceil(n/2)];
timelimit = 1000;
frameskip = 10;

for b = [0.01 0.02 0.05 0.10 0.25 0.5]
    ystam(n, ...
        'BranchingFactor', b, ...
        'TurningFactor', 0.1, ...
        'Gse', 0.99, ...
        'ECM', [5 2 0.02 0.1 0.5], ...
        'ShowRun', true, ...
        'ShowECM', false, ...
        'MaxTrials', 1, ...
        'GrowthMode', 'radial', ...
        'NumSeeds', [num_sources n], ...
        'SetRoot', seed_locations, ...
        'SetGoal', [ceil(n/2)+ceil(n/4) ceil(n/2)+ceil(n/4)], ...
        'ColorCode', randi(255, num_sources, 3)/255, ...
        'Continuous', true, ...
        'Feedback', true, ...
        'TimeLimit', timelimit)
end