%% EG_CHEM_R
% Effect of chemorepulsive forces with some radius around each tile
% A chemorepellant field is left whenever a path disassembles
% The goal is to see if it can navigate intelligently

n = 40;
ystam(n, ...
    'Gse', 0.99, ...
    'BranchingFactor', 0.5, ...
    'ECM', [-1 0.5 0.1 0.05 0.1], ...
    'CMode', [3 10 0 0], ...
    'MaxTrials', 1, ...
    'NumSeeds', [1 1], ...
    'SetGoal', [ceil(n/2), n], ...     
    'ShowRun', true, ...
    'ShowECM', true, ...
    'Feedback', true, ...
    'Continuous', true)