%% EG_CHEM_GA
% Effect of target tile emitting chemoattractive gradient with 
% strength s, radius r, first order decaying with distance

n = 50;
ystam(n, ...
    'Gse', 0.2, ...
    'BranchingFactor', 0.5, ...
    'MaxTrials', 1, ...
    'ECM', [3 0.5 0.01 0.01 0.1], ...
    'ShowECM', true, ...
    'TimeLimit', 5000, ...
    'CMode', [0 0 5 50], ...
    'NumSeeds', [1 1], ...,
    'SetGoal', [ceil(n/2), n], ...
    'ShowRun', true, ...
    'ShowHeatMap', true, ...
    'Continuous', true)