%% EG_DEADZONE
% Navigating around an obstacle in linear mode

n = 40;
for bf = [0.1 0.25 0.5]
    for dzs = [0 -1 -3 -5]
        ystam(n, ...
            'Gse', 1, ...
            'BranchingFactor', bf, ...
            'MaxTrials', 100, ...
            'ECM', [5 2 0.01 0.5 0.2 0], ...
            'TimeLimit', 1000, ...
            'Feedback', true, ...
            'ShowRun', false, ...
            'ShowHeatMap', false, ...
            'ShowECM', false, ...
            'Continuous', false, ...
            'NumSeeds', [1 0], ...
            'SetGoal', [ceil(n/2), n], ...
            'DeadZone', [0.3 0.425 0.0675 0.15], ... % The last column deadzone is [1 1/n 1/n 1], but it seems to create some conflicting behavior with the feedback path
            'DeadZoneECM', [dzs 3 1])
    end
end