%% EG_ECM_SAMPLE   
% Runs a basic case to verify the memory layer is working

n = 50;
ystam(n, ...
    'Gse', 0.9, ...
    'BranchingFactor', 0.05, ...
    'ECM', [5 0.5 0.01 0.05 1], ...
    'Continuous', true, ...
    'Feedback', true, ...
    'ShowRun', true, ...
    'ShowECM', true, ...
    'MaxTrials', 1, ...
    'SetGoal', [ceil(n/2), n], ...
    'GrowthMode', "linear")
