%% EG_ECM_HIT
% Effect of extracellular matrix on hit time
% Run for feedback on and off
% ECM improves hit time with and without feedback, with feedback amplifying
% effects

for feedback = [true false]
    for n = [40 50 60 70 80]
        for gse = [0.8 0.85 0.9 0.95 0.99 0.995]
            for ecms = [5 3 2 1]
                ystam(n, ...
                    'Gse', gse, ...
                    'BranchingFactor', 0.1, ...
                    'ECM', [ecms 0.5 0.2 -0.1 0.25], ...
                    'ShowECM', false, ...
                    'SaveVideo', '', ...
                    'FrameSkip', 10, ...
                    'Filename', 'ECM_HIT', ...
                    'NumSeeds', [1 1], ...
                    'SetGoal', [ceil(n/2), n], ...
                    'MaxTrials', 1, ...
                    'TimeLimit', 1000, ...
                    'Continuous', true, ...
                    'Feedback', true, ...
                    'ShowRun', true)
                return
            end
        end
    end
end
