%% EG_ECM_RATE
% Effect of extracellular matrix on speed of assembly
% How long does it typically take the assembly to terminate (reach the
%   other side)
% Expected results: Higher ecms improves forward rate
%                   Higher mdr improves forward rate

for gse = rand(1, 20)  % Generates randomly distributed data points
    for n = [20 30 40 50 60 70 80]
        ystam(n, ...
            'Gse', gse, ...
            'BranchingFactor', 0.05, ...
            'ECM', [5 0 0.01 0.05 1], ...
            'ShowRun', true, ...
            'ShowECM', true, ...
            'MaxTrials', 1, ...
            'ExportHits', true)
    end
end