%% EG_FB_HIT
% Hit time comparison with and without feedback

n = 50; % grid size

% Run for illustration purposes only
% ystam(n, ...
%     'Gse', 0.8, ...
%     'BranchingFactor', 0.15, ...
%     'MaxTrials', 1, ...
%     'TimeLimit', 500, ...
%     'CMode', [5 5 0 0], ...
%     'ECM', [5 1 0.1 0.1 1 0], ...
%     'Continuous', true, ...
%     'Feedback', true, ...
%     'ShowRun', true, ...
%     'ShowECM', false, ...
%     'ExportImages', '', ...
%     'Filename', 'FeedbackDemo5', ...
%     'SaveVideo', 'g', ...
%     'FrameSkip', 1, ...
%     'NumSeeds', [1 1], ...
%     'SetGoal', [ceil(n/2), n])

%% Run for testing purposes
gse = 0.999;
ystam(n, ...
    'Gse', gse, ...
    'BranchingFactor', 0.5, ...
    'MaxTrials', 1, ...
    'TimeLimit', 500, ...
    'Continuous', true, ...
    'Feedback', true, ...
    'CalcFeedbackOnly', false, ...
    'ExportHits', true, ...
    'Filename', ['feedback_on,gse', num2str(gse)], ...
    'NumSeeds', [1 1], ...
    'SetGoal', [ceil(n/2), n], ...
    'ShowRun', true)

% Different reverse rates
for gse = [0.95 0.975 0.985 0.995]
    % Calculating the connected time
    % With feedback
    ystam(n, ...
        'Gse', gse, ...
        'BranchingFactor', 0.5, ...
        'MaxTrials', 100, ...
        'TimeLimit', 5000, ...
        'Continuous', true, ...
        'Feedback', true, ...
        'CalcFeedbackOnly', true, ...
        'ExportHits', true, ...
        'Filename', ['feedback_on,gse', num2str(gse)], ...
        'NumSeeds', [1 1], ...
        'SetGoal', [ceil(n/2), n], ...
        'ShowRun', true)

    % Without feedback
    ystam(n, ...
        'Gse', gse, ...
        'BranchingFactor', 0.5, ...
        'MaxTrials', 100, ...
        'TimeLimit', 1000, ...
        'Continuous', true, ...
        'Feedback', false, ...
        'CalcFeedbackOnly', true, ...
        'ExportHits', true, ...
        'Filename', ['feedback_off,gse', num2str(gse)], ...
        'NumSeeds', [1 1], ...
        'SetGoal', [ceil(n/2), n], ...
        'ShowRun', true)
end