%% EG_TILE_BIAS
% Changing the relative concentration of tiles based on their output
% direction controls the overall orientation of the assembly
% d: indices correspond to [NL NR EU ED SR SL WD WU]

n = 200;
gse = 1.0;
bf = 0.25;

for bias = [0.1 0.25 0.5 0.75 1.0]
    ystam(n, ...
        'Gse', gse, ...
        'BranchingFactor', bf, ...
        'MaxTrials', 1, ...
        'NumSeeds', [1 0], ...
        'TileDirBias', [1 1 bias 1 1 1 1 1], ...
        'ShowRun', true, ...
        'TimeLimit', n, ...
        'Feedback', true, ...
        'Continuous', false)

    ystam(n, ...
        'Gse', gse, ...
        'BranchingFactor', bf, ...
        'MaxTrials', 1, ...
        'NumSeeds', [1 0], ...
        'TileDirBias', [1 1 1 bias 1 1 1 1], ...
        'ShowRun', true, ...
        'TimeLimit', n, ...
        'Feedback', true, ...
        'Continuous', false)
end
