%% EG_TILECONC
% Effect of tile concentration on average assembly size

n = 40;
list_tc_max = [5 10 20 40 80 160];
Kd = 1;
for tc_max = list_tc_max
    ystam(n, ...
    'Gse', 0.95, ...
    'BranchingFactor', 0.5, ...
    'ShowRun', false, ...
    'ShowECM', false, ...
    'ECM', [5 3 0.01 0.1 0.2 0], ...
    'MaxTrials', 1, ...
    'TimeLimit', 100, ...
    'Feedback', true, ...
    'Continuous', true, ...
    'NumSeeds', [1 1], ...
    'SetGoal', [ceil(n/2), n], ...
    'TileConc', [Kd, tc_max], ...
    'Buffering', 0)
end


% The following need to be added to the parameters to save the populations
%'SavePopulations', true, ...
%'ColorCode', [0 0 0], ...
%        'SaveVideo', '', ...
%        'FrameSkip', 10, ... % This can be changed to anything less than the time limit